# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('mongo_id', models.CharField(max_length=50)),
            ],
        ),
    ]
